#!/usr/bin/env python
# -*- coding: utf-8 -*-


"""
An IRC bot that must be instantiated with a brain (see modules/brain.py)
"""


# twisted imports
from twisted.words.protocols import irc
from twisted.internet import reactor, protocol
from twisted.python import log, rebuild

import modules.brain

# system imports
import getpass, sys

class BotClient(irc.IRCClient):
    """
    A simple wrapper around irc.IRCClient that will try to stay connected to 
    the IRC server and 
    """
    
    def __init__(self):
        try:
            b = rebuild.rebuild(modules.brain, doLog=0)
        except:
            b = modules.brain

        self.lineRate   = None
        self.brain      = b.DNSBot()
        self.nickname   = self.brain.name
        self.username   = self.brain.username
    
    def connectionMade(self):
        """Called when a connection is made"""
        irc.IRCClient.connectionMade(self)
        # hand a copy of self to self.brain (so the bot can talk to IRC)
        self.brain.connectionMade(self, secret=self.factory.getSecret())

    def connectionLost(self, reason):
        """Called when a connection is lost"""
        irc.IRCClient.connectionLost(self, reason)
        # tell the brain it's disconnected?
        self.brain.connectionLost()

    ## callbacks for events
    def signedOn(self):
        """Called when bot has succesfully signed on to server."""
        self.setNick(self.brain.name)
        for channel in self.brain.channels:
            self.join(channel.strip())

    def joined(self, channel, *args):
        """This will get called when the bot joins the channel."""
        self.brain.joined(channel)

    def names(self, channel):
        """Send a NAMES request to a channel"""
        if not channel:
            return
        msg = "NAMES {0}".format(channel)
        self.sendLine(msg)

    def irc_RPL_NAMREPLY(self, prefix, reply):
        """This gets called when we get a reply to NAMES"""
        channel = reply[2]
        names = reply[3].split()
        self.brain.gotNames(channel, names)

    def userJoined(self, user, channel):
        """Called when a user joins a channel"""
        self.names(channel)

    def userLeft(self, user, channel):
        """Called when a user leaves a channel"""
        self.names(channel)

    # XXX This does not appear to get called on nick change
    #def userRenamed(self, oldname, newname):
    #    """Called when a user changes nick???"""
    #    self.names(channel)

    def left(self, channel):
        """This will get called when the bot leaves a channel."""

    def reload(self):
        self.__init__()
        self.brain.connectionMade(self, secret=self.factory.getSecret())
        self.setNick(self.brain.name)

    def privmsg(self, user, replyTo, msg):
        """This will get called when the bot receives a message."""
        mask = None
        if user.count('!') > 0:
            (user, mask) = user.split('!', 1)

        if replyTo == self.nickname:
            replyTo = user

        self.brain.gotMsg(user, replyTo, msg)

    def action(self, user, replyTo, act):
        """This will get called when the bot sees someone do an action."""
        user = user.split('!', 1)[0]

        if replyTo == self.nickname:
            replyTo = user

        self.brain.gotAction(user, replyTo, act)

    def irc_NICK(self, prefix, params):
        """Called when an IRC user changes their nickname."""
        old_nick = prefix.split('!')[0]
        new_nick = params[0]

    def irc_INVITE(self, mask, where):
        print "just got an invite"
        """Called when someone invites me to a channel"""
        (nick, channel) = where
        self.join(channel)
        self.msg(channel, "Thanks, {0}!".format(mask.split('!')[0]))

    ## maintenance callback
    def irc_PING(self, prefix, params):
        """Called when we get PINGed. Maybe."""
        self.brain.writeState()

        ### ...aand, the pong (forgot this earlier)
        self.sendLine("PONG %s" % params[-1])

class IRCClientFactory(protocol.ClientFactory):
    """
    A factory for IRC Clients.
    A new protocol instance will be created each time we connect to the server.
    """

    def __init__(self):
        self.protocol = BotClient

    def getSecret(self):
        return None

    def clientConnectionLost(self, connector, reason):
        """If we get disconnected, reconnect to server."""
        connector.connect()

    def clientConnectionFailed(self, connector, reason):
        print "connection failed:", reason
        reactor.stop()

def usage(exitcode):
    print "Usage: {0} [server]".format(sys.argv[0])
    sys.exit(exitcode)

if __name__ == '__main__':

    try:
        server = sys.argv[1]
    except IndexError:
        usage(1)

    # initialize logging
    log.startLogging(sys.stdout)

    # create factory protocol and application
    f = IRCClientFactory()

    # connect factory to this host and port
    ## the old way
    reactor.connectTCP(server, 6667, f)

    # run bot
    reactor.run()

